Repository samply/dktk-explorer, pull requests merged in 2023-09, with the labels that each got.

#27 refactor: changed the UICC Searchtee and added 'I' and 'IC'
  src/assets/catalogue.ts
Labels: refactoring

#30 Remove global Flag from Diagnosis Regex
  src/app/main/main.component.ts
Labels: bug

#32 chore: bump lens 0.1.4 -> 0.1.5
  package-lock.json
Labels: dependencies
